### ISSUE TITLE
Where to buy?

### ISSUE THREAD

**Issue by yzheka** [mafe72/3D-Printer-Filament-Width-Sensor#1]
Where can I buy this sensor board? I looked at mini-mods.com shop but have not found it.

**Comment by mafe72** [comment]
Greetings,

Thanks for your interest on the 3D-Printer-Filament-Width-Sensor, due to the chip shortage I have not been able to buy TSL1401CL sensors at a reasonable price to restock this item.

I will keep you posted once I have new stock of this sensor.

Best regards,
Eladio

From: ***@***.***>
Sent: Wednesday, September 29, 2021 6:13 AM
To: ***@***.***>
Cc: ***@***.***>
Subject: [mafe72/3D-Printer-Filament-Width-Sensor] Where to buy? (#1)


Where can I buy this sensor board? I looked at mini-mods.com shop but have not found it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmafe72%2F3D-Printer-Filament-Width-Sensor%2Fissues%2F1&data=04%7C01%7C%7C000a40fde26b4b628f5f08d9833a360a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637685108303511629%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dYG4Xwjmm26adZuqlbtrXRA8BCUcfgSZvw4IT32%2Fl7M%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG5FZMUQP3DZ7ZM6A2NV3M3UELYGZANCNFSM5E7TUHNA&data=04%7C01%7C%7C000a40fde26b4b628f5f08d9833a360a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637685108303521623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JiqKGvRPtZplAVUxI%2FdDE6nhnzPzFksD4DTy%2BcTfBOo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C000a40fde26b4b628f5f08d9833a360a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637685108303521623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cRJ0emScxvKeO0iLHU0%2FO2VDsrsIHKGQsVCqCttuUB8%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C000a40fde26b4b628f5f08d9833a360a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637685108303531618%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JABHpyw0YUj0FIMWQZz8QL1Z5HjiOFGfwFNKzwVll18%3D&reserved=0>.

**Comment by yzheka** [comment]
I will appreciate for any updates on this. Thank you
